addiction/urls.py
from django.urls import path
# 引入views.py
from . import views

app_name = 'addiction'

urlpatterns = [
    # 文章列表
    path('addiction-list/', views.addiction_list, name='addiction_list'),
    # 文章详情
    path('addiction-detail/<int:id>/', views.addiction_detail, name='addiction_detail'),
    # 写文章
    path('addiction-create/', views.addiction_create, name='addiction_create'),
    # 删除文章
    path('addiction-delete/<int:id>/', views.addiction_delete, name='addiction_delete'),
    # 安全删除文章
    path('addiction-safe-delete/<int:id>/', views.addiction_safe_delete, name='addiction_safe_delete'),
    # 更新文章
    path('addiction-update/<int:id>/', views.addiction_update, name='addiction_update'),
    # 点赞 +1
    path('increase-likes/<int:id>/', views.IncreaseLikesView.as_view(), name='increase_likes'),

    # 列表类视图
    path('list-view/', views.AddictionListView.as_view(), name='list_view'),
    # 详情类视图
    path('detail-view/<int:pk>/', views.AddictionDetailView.as_view(), name='detail_view'),
    # 创建类视图
    path('create-view/', views.AddictionCreateView.as_view(), name='create_view'),
]

mental/urls.py
from django.urls import path
# 引入views.py
from . import views

app_name = 'mental'

urlpatterns = [
    # 文章列表
    path('mental-list/', views.mental_list, name='mental_list'),
    # 文章详情
    path('mental-detail/<int:id>/', views.mental_detail, name='mental_detail'),
    # 写文章
    path('mental-create/', views.mental_create, name='mental_create'),
    # 删除文章
    path('mental-delete/<int:id>/', views.mental_delete, name='mental_delete'),
    # 安全删除文章
    path('mental-safe-delete/<int:id>/', views.mental_safe_delete, name='mental_safe_delete'),
    # 更新文章
    path('mental-update/<int:id>/', views.mental_update, name='mental_update'),
    # 点赞 +1
    path('increase-likes/<int:id>/', views.IncreaseLikesView.as_view(), name='increase_likes'),

    # 列表类视图
    path('list-view/', views.MentalListView.as_view(), name='list_view'),
    # 详情类视图
    path('detail-view/<int:pk>/', views.MentalDetailView.as_view(), name='detail_view'),
    # 创建类视图
    path('create-view/', views.MentalCreateView.as_view(), name='create_view'),
]

my_blog/urls.py
from django.contrib import admin
# 记得引入include
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

import notifications.urls

from addiction.views import addiction_list
from . import views


# 存放了映射关系的列表
urlpatterns = [
    path('admin/', admin.site.urls),
    # home
    path('', views.get_homepage, name='home'),
    # 重置密码app
    path('password-reset/', include('password_reset.urls')),
    # 新增代码，配置app的url
    path('addiction/', include('addiction.urls', namespace='addiction')),
    # 新增代码，配置app的url
    path('mental/', include('mental.urls', namespace='mental')),
    # 用户管理
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    # comment_addiction
    path('comment_addiction/', include('comment_addiction.urls', namespace='comment_addiction')),
    # comment_mental
    path('comment_mental/', include('comment_mental.urls', namespace='comment_mental')),
    # djang-notifications
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    # notice
    path('notice/', include('notice.urls', namespace='notice')),
    # django-allauth
    path('accounts/', include('allauth.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notice/urls.py
from django.urls import path
# 引入views.py
from . import views

app_name = 'notice'

urlpatterns = [
    # 通知列表
    path('list/', views.CommentNoticeListView.as_view(), name='list'),
    path('update/', views.CommentNoticeUpdateView.as_view(), name='update'),
]

userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    # 用户登录
    path('login/', views.user_login, name='login'),
    # 用户退出
    path('logout/', views.user_logout, name='logout'),
    # 用户注册
    path('register/', views.user_register, name='register'),
    # 用户删除
    path('delete/<int:id>/', views.user_delete, name='delete'),
    # 用户信息
    path('edit/<int:id>/', views.profile_edit, name='edit'),
]

templates/back_to_top_func.html
<!-- Author: 鹦鹉 -->
<!-- https://ezbox.idv.tw/131/back-to-top-button-without-images -->
<button type="button" id="BackTop" class="toTop-arrow" style="z-index: 100;"></button>

<script>
    // 向上滚动的函数
    $(function () {
        $('#BackTop').click(function () {
            $('html,body').animate({scrollTop: 0}, 500);
        });
        $(window).scroll(function () {
            if ($(this).scrollTop() > 300) {
                $('#BackTop').fadeIn(300);
            } else {
                $('#BackTop').stop().fadeOut(300);
            }
        }).scroll();
    });
</script>

<style>
    /* 按钮边框的大小、位置、样式 */
    .toTop-arrow {
        width: 3.5rem;
        height: 3.5rem;
        padding: 0;
        margin: 0;
        border: 0;
        border-radius: 33%;
        opacity: 0.7;
        background: black;
        cursor: pointer;
        position: fixed;
        right: 1.5rem;
        bottom: 1.5rem;
        display: none;
    }

    /* 绘制按钮中的向上箭头 */
    .toTop-arrow::before, .toTop-arrow::after {
        width: 31px;
        height: 7px;
        border-radius: 3px;
        background: orange;
        position: absolute;
        content: "";
    }

    .toTop-arrow::before {
        transform: rotate(-45deg) translate(0, -50%);
        left: 0.4rem;
    }

    .toTop-arrow::after {
        transform: rotate(45deg) translate(0, -50%);
        right: 0.4rem;
    }

    /* 取消点击按钮时的聚焦 */
    .toTop-arrow:focus {
        outline: none;
    }
</style>

templates/base.html
<!-- 载入静态文件 -->
{% load staticfiles %}

<!DOCTYPE html>
<!-- 网站主语言 -->
<html lang="zh-cn">

<head>
    <!-- 网站采用的字符编码 -->
    <meta charset="utf-8">
    <!-- 网站标题 -->
    <title>{% block title %}{% endblock %}</title>
    <!-- 引入bootstrap的css文件 -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <!-- 引入monikai.css -->
    <link rel="stylesheet" href="{% static 'md_css/monokai.css' %}">
    
    <link
            rel="stylesheet"
            href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.14.0/css/all.min.css"
    >
</head>

<body>

<!-- 引入导航栏 -->
{% include 'header.html' %}
<!-- 预留具体页面的位置 -->
<div id="wrapper">
    {% block content %}{% endblock content %}
    <div id="push"></div>
</div>
<!-- 引入注脚 -->
{% include 'footer.html' %}

<!-- bootstrap.js 依赖 jquery.js 和popper.js，因此在这里引入 -->
<script src="{% static 'jquery/jquery-3.3.1.js' %}"></script>

<!-- 2020.07.22: popper.js 更新为远程调用的形式 -->
{#<script src="{% static 'popper/popper-1.14.4.js' %}"></script>#}
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1-lts/dist/umd/popper.min.js"></script>

<!-- 引入bootstrap的js文件 -->
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
<!-- 引入layer.js -->
<script src="{% static 'layer/layer.js' %}"></script>

{% block script %}{% endblock script %}

{% include 'back_to_top_func.html' %}


<style>
    html, body {
        height: 100vh;
        margin: 0;
        background-color:#F5F5DC;
    }

    #wrapper {
        min-height: 90vh;
        margin-bottom: -40px;
    }

    #footer,
    #push {
        height: 60px;
    }
</style>

</body>

</html>

templates/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Touch Hospital Medical Free HTML5 Web Temp</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<meta name="description" content="" />
<meta name="author" content="http://webthemez.com" />
<!-- css -->
<link href="css/bootstrap.min.css" rel="stylesheet" />
<link href="css/fancybox/jquery.fancybox.css" rel="stylesheet">
<link href="css/jcarousel.css" rel="stylesheet" />
<link href="css/flexslider.css" rel="stylesheet" />
<link href="css/style.css" rel="stylesheet" />
 
<!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
<!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

</head>
<body>
<div id="wrapper">
	<!-- start header -->
	<header>
        <div class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                  <a class="navbar-brand" href="index.html"><img src="img/logo.png" alt="logo"/></a>
                </div>
                <div class="navbar-collapse collapse ">
                    <ul class="nav navbar-nav">
                        <li><a href="index.html">Home</a></li> 
						<li><a href="about.html">About Us</a></li>
						<li><a href="services.html">Services</a></li>
                        <li><a href="portfolio.html">Portfolio</a></li>
                        <li><a href="pricing.html">Pricing</a></li>
                        <li class="active"><a href="contact.html">Contact</a></li>
                    </ul>
                </div>
            </div>
        </div>
	</header><!-- end header -->
	<section id="inner-headline">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<h2 class="pageTitle">Contact Us</h2>
			</div>
		</div>
	</div>
	</section>
	<section id="content">
	
	<div class="container">
		<div class="row"> 
							<div class="col-md-12">
								<div class="about-logo">
									<h3>Get in Touch!</h3>
									<p>If you have any question or need any help, feel free to contact us!</p>
                                    	<p>If you have any question or need any help, feel free to contact us!</p>
								</div> 
							</div>
						</div>
	<div class="row">
								<div class="col-md-6">
									<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do tempor.</p>
									<div class="done">
			<div class="alert alert-success">
				<button type="button" class="close" data-dismiss="alert">×</button>
				Your message has been sent. Thank you!
			</div>
		</div>
									<div class="contact-form">
											
		<form method="post" action="contact.php" id="contactform" class="contact">
											<div class="form-group has-feedback">
												<label for="name">Name*</label>
												<input type="text" class="form-control" name="name" placeholder="">
												<i class="fa fa-user form-control-feedback"></i>
											</div>
											<div class="form-group has-feedback">
												<label for="email">Email*</label>
												<input type="email" class="form-control" name="email" placeholder="">
												<i class="fa fa-envelope form-control-feedback"></i>
											</div>
 
											<div class="form-group has-feedback">
												<label for="message">Message*</label>
												<textarea class="form-control" rows="6" name="comment" placeholder=""></textarea>
												<i class="fa fa-pencil form-control-feedback"></i>
											</div>
											<input type="submit" value="Submit" id="submit" class="submit btn btn-default">
										</form>
										 
										
									</div>
								</div>
								<div class="col-md-6">
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script><div style="overflow:hidden;height:500px;width:600px;"><div id="gmap_canvas" style="height:500px;width:600px;"></div><style>#gmap_canvas img{max-width:none!important;background:none!important}</style><a class="google-map-code" href="http://www.trivoo.net" id="get-map-data">trivoo</a></div><script type="text/javascript"> function init_map(){var myOptions = {zoom:14,center:new google.maps.LatLng(40.805478,-73.96522499999998),mapTypeId: google.maps.MapTypeId.ROADMAP};map = new google.maps.Map(document.getElementById("gmap_canvas"), myOptions);marker = new google.maps.Marker({map: map,position: new google.maps.LatLng(40.805478, -73.96522499999998)});infowindow = new google.maps.InfoWindow({content:"<b>The Breslin</b><br/>2880 Broadway<br/> New York" });google.maps.event.addListener(marker, "click", function(){infowindow.open(map,marker);});infowindow.open(map,marker);}google.maps.event.addDomListener(window, 'load', init_map);</script>
								</div>
							</div>
	</div>
 
	</section>
	<footer>
	<div class="container">
		<div class="row">
			<div class="col-lg-3">
				<div class="widget">
					<h5 class="widgetheading">Our Contact</h5>
					<address>
					<strong>Bistro company Inc</strong><br>
					JC Main Road, Near Silnile tower<br>
					 Pin-21542 NewYork US.</address>
					<p>
						<i class="icon-phone"></i> (123) 456-789 - 1255-12584 <br>
						<i class="icon-envelope-alt"></i> email@domainname.com
					</p>
				</div>
			</div>
			<div class="col-lg-3">
				<div class="widget">
					<h5 class="widgetheading">Quick Links</h5>
					<ul class="link-list">
						<li><a href="#">Latest Events</a></li>
						<li><a href="#">Terms and conditions</a></li>
						<li><a href="#">Privacy policy</a></li>
						<li><a href="#">Career</a></li>
						<li><a href="#">Contact us</a></li>
					</ul>
				</div>
			</div>
			<div class="col-lg-3">
				<div class="widget">
					<h5 class="widgetheading">Latest posts</h5>
					<ul class="link-list">
						<li><a href="#">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</a></li>
						<li><a href="#">Pellentesque et pulvinar enim. Quisque at tempor ligula</a></li>
						<li><a href="#">Natus error sit voluptatem accusantium doloremque</a></li>
					</ul>
				</div>
			</div>
			<div class="col-lg-3">
					<div class="widget">
					<h5 class="widgetheading">Recent News</h5>
					<ul class="link-list">
						<li><a href="#">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</a></li>
						<li><a href="#">Pellentesque et pulvinar enim. Quisque at tempor ligula</a></li>
						<li><a href="#">Natus error sit voluptatem accusantium doloremque</a></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
	<div id="sub-footer">
		<div class="container">
			<div class="row">
				<div class="col-lg-6">
					<div class="copyright">
						<p>
							<span>&copy; Touch Hospital Medical 2015 All right reserved. By </span><a href="http://webthemez.com" Bistro="_blank">WebThemez</a>
						</p>
					</div>
				</div>
				<div class="col-lg-6">
					<ul class="social-network">
						<li><a href="#" data-placement="top" title="Facebook"><i class="fa fa-facebook"></i></a></li>
						<li><a href="#" data-placement="top" title="Twitter"><i class="fa fa-twitter"></i></a></li>
						<li><a href="#" data-placement="top" title="Linkedin"><i class="fa fa-linkedin"></i></a></li>
						<li><a href="#" data-placement="top" title="Pinterest"><i class="fa fa-pinterest"></i></a></li>
						<li><a href="#" data-placement="top" title="Google plus"><i class="fa fa-google-plus"></i></a></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
	</footer>
</div>
<a href="#" class="scrollup"><i class="fa fa-angle-up active"></i></a>
<!-- javascript
    ================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="js/jquery.js"></script>
<script src="js/jquery.easing.1.3.js"></script>
<script src="js/bootstrap.min.js"></script>
<script src="js/jquery.fancybox.pack.js"></script>
<script src="js/jquery.fancybox-media.js"></script> 
<script src="js/portfolio/jquery.quicksand.js"></script>
<script src="js/portfolio/setting.js"></script>
<script src="js/jquery.flexslider.js"></script>
<script src="js/animate.js"></script>
<script src="js/custom.js"></script>
<script src="js/validate.js"></script>
</body>
</html>

templates/footer.html
{% load staticfiles %}
<!-- Footer -->
<footer class="navbar-fixed-bottom" id="footer" style="height:40px;background-color:rgba(110, 139, 61, 0.7 )">
    <div class="container">
        <h5 class="m-0 text-center text-white"> Matrix Team 2022, UNSW</h5>
    </div>
</footer>

templates/header.html
{% load notifications_tags %}
{% notifications_unread as unread_count %}
{% load static %}

<!-- 定义导航栏 -->
<div id="wrapper" class="home-page" >
<nav class="navbar navbar-expand-lg navbar-default navbar-static-top" style="background-color:rgba(110, 139, 61, 0.7);opacity:0.6">
    <div class="container">
        <!-- 导航栏商标 -->
        <a class="navbar-header" href="{% url 'home' %}" >Healcare for Social Media Issues</a>

        <div>
            <ul class="navbar-collapse collapse ">
                <div class="navbar-collapse collapse ">
                    <ul class="nav navbar-nav">
                        <a class="navbar-brand" href="{% url 'addiction:addiction_list' %}">Articles</a>
                        <a class="navbar-brand" href="{% url 'mental:mental_list' %}">Forum</a>
                        <a class="navbar-brand" href="{% url 'mental:mental_list' %}">Contact us</a>
                    </ul>
                </div>


                <!-- Django的 if 模板语句 -->
                {% if user.is_authenticated %}
                    <!-- 如果用户已经登录，则显示用户名下拉框 -->
                    <ul class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {% if unread_count %}
                                <svg viewBox="0 0 8 8"
                                     width="8px"
                                     height="8px">
                                    <circle cx="4"
                                            cy="4"
                                            r="4"
                                            fill="#ff6b6b"
                                    ></circle>
                                </svg>
                            {% endif %}
                            {{ user.username }}
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url "notice:list" %}">Notification
                                {% if unread_count %}
                                    <span class="badge badge-danger">{{ unread_count }}</span>
                                {% endif %}
                            </a>
                            <a class="dropdown-item" href='{% url "userprofile:edit" user.id %}'>User Profile</a>
                            <a class="dropdown-item" href="#" onclick="user_delete()">User Delete</a>
                            <a class="dropdown-item" href='{% url "userprofile:logout" %}'>Logout</a>
                        </div>
                    </ul>
                <!-- 如果用户未登录，则显示 “登录” -->
                {% else %}
                    <div class="navbar-collapse collapse ">
                        <ul class="nav navbar-nav">
                            <a class="navbar-brand" href="{% url 'account_login' %}">Login</a>
                        </ul>
                    </div>
                <!-- if 语句在这里结束 -->
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

{% if user.is_authenticated %}
<form 
    style="display:none;" 
    id="user_delete"
    action="{% url 'userprofile:delete' user.id %}" 
    method="POST"
>
{% csrf_token %}
    <button type="submit">Submit</button>
</form>
    <script>
        function user_delete() {
            // 调用layer弹窗组件
            layer.open({
                title: "Confirm to delete",
                content: "Are you sure to delete the user profile? ",
                yes: function(index, layero) {
                    $('form#user_delete button').click();
                    layer.close(index);
                },
            })
        }
    </script>
{% endif %}

<style>
    a {
        color:white;
    }
</style>

templates/homepage.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}
{% load staticfiles %}
{% load my_filters_and_tags %}

    <meta charset="utf-8">
    <title>Touch Hospital Medical Free HTML5 Bootstrap Template</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="" />
    {% comment %} <meta name="author" content="http://webthemez.com" /> {% endcomment %}
    <!-- css -->
    {% comment %} <link href="css/bootstrap.min.css" rel="stylesheet" /> {% endcomment %}
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/fancybox/jquery.fancybox.css' %}"> 
    <link rel="stylesheet" href="{% static 'css/flexslider.css' %}"/> 
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>

 
<!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
<!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

<div id="wrapper" class="home-page">
	<!-- start header -->
    {% include 'header.html' %}
	<!-- end header -->

    <!-- 写入 base.html 中定义的 content -->
    {% block content %}
    <div class="container">
        <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel" style='width:100%;height:20%'>
            <ol class="carousel-indicators">
            <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
            <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="{% static 'img/e1.jpg' %}" class="d-block w-100"  alt="..." height='600px'>
                <div class="carousel-caption d-none d-md-block">
                <h5>Social Media Addiction</h5>
                <p>Live in the virtual in mobile phone.</p>
                </div>
            </div>
            <div class="carousel-item">
                <img src="{% static 'img/e2.jpg' %}" class="d-block w-100" alt="..." height='600px'>
                <div class="carousel-caption d-none d-md-block">
                <h5>Get Over The Social Media</h5>
                <p>Return to the reality.</p>
                </div>
            </div>
            <div class="carousel-item">
                <img src="{% static 'img/e3.jpg' %}" class="d-block w-100" alt="..." height='600px'>
                <div class="carousel-caption d-none d-md-block">
                <h5>You are not alone.</h5>
                <p>We can help you deal with you concerns.</p>
                </div>
            </div>
            </div>
            <button class="carousel-control-prev" type="button" data-target="#carouselExampleCaptions" data-slide="prev" style="background:0;border:0;">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-target="#carouselExampleCaptions" data-slide="next" style="background:0;border:0;">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
            </button>
        </div>
	<br/>
	<section class="aboutUs">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="aligncenter"><h2 class="aligncenter">Are You Addicted in Social Media Today?</h2>If you have the following situations, it is time to start paying attention to your habits.</div>
				<br/>
			</div>
		</div> 
		<div class="row">
							<div class="col-md-6">
								<p><h5>If you have the following situations, it is time to start paying attention to your habits.</h5></p>
                        
								<ul class="list-unstyled">
									<li><i class="fa fa-arrow-circle-right pr-10 colored"></i> Are you unable to focus on your work and studies because you browse social media？</li>
									<li><i class="fa fa-arrow-circle-right pr-10 colored"></i> Are you lacking in real-world friends because you spend a lot of time chatting on social media？</li>
									<li><i class="fa fa-arrow-circle-right pr-10 colored"></i> Are you constantly staying up late because of social media, eating irregularly, causing diseases of your digestive system or organs？</li>
									<li><i class="fa fa-arrow-circle-right pr-10 colored"></i> Do you become anxious, afraid of real social interaction or fall into depression due to prolonged use of social media?</li>
								</ul>
								
							</div>
							<div class="col-md-6">
								<p><h5>Why you join us?</h5></p>
			
								<ul class="list-unstyled">
									<li><i class="fa fa-arrow-circle-right pr-10 colored"></i> Our website collects Internet addiction cases from all over the world, which can be used as a reference for you.</li>
									<li><i class="fa fa-arrow-circle-right pr-10 colored"></i> The active users of the platform are as high as 90%, and you can make friends and meet offline.</li>
									<li><i class="fa fa-arrow-circle-right pr-10 colored"></i> Have the world's top mental medical team to answer all kinds of problems in your life.</li>
									<li><i class="fa fa-arrow-circle-right pr-10 colored"></i> Have the opportunity to get one-on-one consultation for free, so that you can experience a new life and love yourself more.</li>
								</ul>
							</div>
						</div>
	
	</div>
	</section>

</div>
<a href="#" class="scrollup"><i class="fa fa-angle-up active"></i></a>
<!-- javascript
    ================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery.fancybox.pack.js' %}"></script>
<script src="{% static 'js/jquery.fancybox-media.js' %}"></script> 
<script src="{% static 'js/portfolio/jquery.quicksand.js' %}"></script>
<script src="{% static 'js/portfolio/setting.js' %}"></script>
<script src="{% static 'js/jquery.flexslider.js' %}"></script>
<script src="{% static 'js/animate.js' %}"></script>
<script src="{% static 'js/custom.js' %}"></script> 

{% endblock content %}